name: boliden
description: "A task manager"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  path: ^1.9.0
  injectable: ^2.3.2
  get_it: ^7.6.7
  reactive_forms: ^16.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.2
flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
