name: build
on: workflow_dispatch
jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.4'
      - run: flutter pub get
      - run: flutter build appbundle
      - name: Archive android artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'android-artifacts'
          path: 'build/app/outputs/bundle/release'
  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Archive iOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'ios-artifacts'
          path: 'build/ios/iphoneos'
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build windows
      - name: Archive windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'windows-artifacts'
          path: 'build/windows/runner/Release'
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux
      - name: Archive linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'linux-artifacts'
          path: 'build/linux/x64/release/bundle'
  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter build macos
      - name: Archive macos artifacts
        uses: actions/upload-artifact@v4
        with:
          name: 'macos-artifacts'
          path: 'build/macos/Build/Products/Release/*.app"
